### ISSUE TITLE
To pile on, 1.20 and 1.20.1 Fabric.

### ISSUE THREAD

**Issue by Enaium** [Enaium-FabricMC/NoExpensive#17]
To pile on, 1.20 and 1.20.1 Fabric.
Mod on client and server.

No matter what the max level is set to, 0, 10000, and anywhere in between, the cost always shows as 39.

_Originally posted by @BBloom81 in https://github.com/Enaium-FabricMC/NoExpensive/issues/16#issuecomment-1592138881_

**Comment by Enaium** [comment]
I use the lore to show the cost of repairs so that the mod does not need to be installed on the client side in the next version.
![](https://github.com/Enaium-FabricMC/NoExpensive/assets/32991121/ca2e2f10-0972-46e8-92b8-c579f89e6188)

**Comment by BBloom81** [comment]
Maybe I'm mistaken on the way this mod works.
I thought I could use it to repair tools beyond the normal max level, like my infinity bow.
I also thought it was configurable in that regard rather than costing 39 levels for everything.

If it's only for books, or I'm mistaken, my bad.

[Enchantment Cost 39_01.zip](https://github.com/Enaium-FabricMC/NoExpensive/files/11764107/Enchantment.Cost.39_01.zip)
[Enchantment Cost 39_02.zip](https://github.com/Enaium-FabricMC/NoExpensive/files/11764109/Enchantment.Cost.39_02.zip)

**Comment by Enaium** [comment]
> Maybe I'm mistaken on the way this mod works. I thought I could use it to repair tools beyond the normal max level, like my infinity bow. I also thought it was configurable in that regard rather than costing 39 levels for everything.
> 
> If it's only for books, or I'm mistaken, my bad.
> 
> [Enchantment Cost 39_01.zip](https://github.com/Enaium-FabricMC/NoExpensive/files/11764107/Enchantment.Cost.39_01.zip) [Enchantment Cost 39_02.zip](https://github.com/Enaium-FabricMC/NoExpensive/files/11764109/Enchantment.Cost.39_02.zip)

Don't use the mod on the client side if the mod is on the server side, wait for the next version plz.

**Comment by Enaium** [comment]
Fixed
